"""``fdc_foods`` table: insert-once cache of USDA FoodData Central nutrients.

Rows are written on the first successful FDC lookup for an ``fdc_id`` and are
never updated afterwards. All nutrient values are per 100 g:

* ``energy_kcal_per_100g`` -> FDC nutrient number 208
* ``protein_g_per_100g``   -> FDC nutrient number 203
* ``fat_g_per_100g``       -> FDC nutrient number 204
* ``carbs_g_per_100g``     -> FDC nutrient number 205
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import DateTime, Integer, Numeric, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:  # pragma: no cover
    from app.models.food_log import FoodLog


class FdcFood(Base):
    __tablename__ = "fdc_foods"

    # The FDC identifier itself - not generated by us.
    fdc_id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=False
    )
    food_name: Mapped[str] = mapped_column(String(500), nullable=False)
    energy_kcal_per_100g: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(8, 2), nullable=True
    )
    protein_g_per_100g: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(8, 2), nullable=True
    )
    fat_g_per_100g: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(8, 2), nullable=True
    )
    carbs_g_per_100g: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(8, 2), nullable=True
    )
    cached_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    food_logs: Mapped[List["FoodLog"]] = relationship(back_populates="food")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<FdcFood fdc_id={self.fdc_id} food_name={self.food_name!r}>"
